### ISSUE TITLE
Advanced Git

### ISSUE THREAD

**Issue by cg433n** [ualibraries/tinycon#17]
⚠️ **Add your favorite Git tip or resource in the comments**

**Comment by cg433n** [comment]
`git graph`

**Comment by cg433n** [comment]
A nice visual git graph: `graph = log --graph --abbrev-commit --date=iso --all`

**Comment by cg433n** [comment]
Order all of your tags by date: `list-tags = tag --sort version:refname -n10 -n`

**Comment by cg433n** [comment]
Git Flow

**Comment by cg433n** [comment]
Advanced Git course on Pluralsight

**Comment by Chu-2** [comment]
https://kapeli.com/cheat_sheets/Git.docset/Contents/Resources/Documents/index

**Comment by kevcooper** [comment]
GPG signing commits and tags
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by greenbicycle** [comment]
`git branch --contains <branch-name>`

This has been a life saver recently.

**Comment by jcoliver** [comment]
Not that this is advanced, but one I use quite a bit.
```
git checkout destination-branch
git checkout source-branch file-of-interest
```
For adding changes to an individual _file_ from one branch to another.

**Comment by zensense** [comment]
retrieve a specific file from stash: 

`git checkout stash@{0} -- <filename>`

Note that the integer is the stash level, 0 being the latest stash.

**Comment by MarkFischer** [comment]
If you want to throw away any un-staged an un-committed work on a branch:

    git checkout -- .

Warning! There's no warning or anything, all changes are just wiped and you back to wherever you were when you checked out your current branch.

**Comment by MarkFischer** [comment]
GitHub and BitBucket also both support arbitrary Web Hooks.  So you could trigger your own custom workflow (API, Lambda, etc) to happen on events (Pushes, Merges, Pull Requests etc)

**Comment by dspies** [comment]
https://dotfiles.github.io/
https://github.com/paulirish/dotfiles
Good for tips on gitconfig
