### ISSUE TITLE
Docker and Kubernetes

### ISSUE THREAD

**Issue by cg433n** [ualibraries/tinycon#69]

**Comment by pbarabe** [comment]
+1

**Comment by cg433n** [comment]
@pbarabe Could you use the reaction chooser on the issue? That way we can sort the issue by most reactions.
<img width="797" alt="screen shot 2018-06-29 at 10 21 37 am" src="https://user-images.githubusercontent.com/868735/42105735-546435da-7b86-11e8-80cd-f882f7875a93.png">

**Comment by pbarabe** [comment]
@cg433n Oops - did I do it correctly this time?

**Comment by cg433n** [comment]
https://rominirani.com/tutorial-getting-started-with-kubernetes-with-docker-on-mac-7f58467203fd

**Comment by kevcooper** [comment]
Example docker file: https://bitbucket.org/ua_drupal/terminus-docker-image

**Comment by liquid06** [comment]
Some official tutorials 😄  https://kubernetes.io/docs/tutorials/

**Comment by liquid06** [comment]
This looks fun too https://www.katacoda.com/courses/kubernetes/playground

**Comment by liquid06** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Comment by dspies** [comment]
Free Book from Packt Pub today: Mastering Kubernetes
https://www.packtpub.com//packt/offers/free-learning
