### ISSUE TITLE
tinycon 15

### ISSUE THREAD

**Issue by liquid06** [ualibraries/tinycon#78]
tinycon 15
Main Library room 313
Thursday November 1 at 11:00am
Total time: 1 hour

### Supplies

- Red sticky notes
- Sharpies

### Introduction 

- What is tinycon?
- Say your name and one thing you are learning
- Vote for topics on github!

### Main topic: React 
* Invite participants to work in pairs
* Pass out red sticky notes to each individual or pair
* Remind people to display their red sticky note on their device to alert other participants if they are stuck or need help
* Continue video tutorial https://teamtreehouse.com/library/react-by-example (at https://teamtreehouse.com/library/creating-the-counter)

### Write on sticky notes
* What would you like to learn?
* Feedback
* Email address (if you would like to be added to the listserv)

**Comment by c9rgreen** [comment]
[starter-files.zip](https://github.com/ualibraries/tinycon/files/2539515/starter-files.zip)

**Comment by simpsonw** [comment]
Here are the files I had since last time:

[rsvp.zip](https://github.com/ualibraries/tinycon/files/2539549/rsvp.zip)
